_type: self-hosted

telemetry:
  disable_telemetry_sharing: true

replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: disable

storage:
  type: mongodb
  uri: !env PS_MONGO_URI

port: !env PS_PORT

sync_config:
  path: sync-config.yaml

client_auth:
  supabase: true
  supabase_jwt_secret: !env PS_SUPABASE_JWT_SECRET
  audience: ["authenticated", "powersync-dev", "powersync"]

api:
  tokens:
    - troque-este-token-de-desenvolvimento

system:
  logging:
    level: info
    format: text
